project:
  type: website
  output-dir: docs
execute:
  freeze: auto  
website:
  title: "landing-page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: GISHub.qmd
        text: GIS Hub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



